config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/force_rate.rb
# frozen_string_literal: true

class ForceRate < ApplicationRecord
  enum valute: { USD: 0 }, _prefix: true

  validates :rate, presence: true, numericality: true
  validates :valute, presence: true
  validates :expired_at, presence: true,
                         timeliness: {
                           on_or_after: -> { DateTime.current }, # rubocop:disable Style/DateTime
                           before: -> { 2.days.from_now }
                         }

  after_commit :broadcast_rate

  def self.get!(valute)
    return unless (forced_rate = find_by(valute: valute))

    if DateTime.current > forced_rate.expired_at # rubocop:disable Style/DateTime
      forced_rate.destroy
      nil
    else
      forced_rate.rate
    end
  end

  def broadcast_rate
    RateBroadcastJob.perform_later
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  USD = 'USD'

  def index
    @usd_rate = Operations::Rates::Take.new.call(**rate_take_opts).value_or('unknown')
  end

  private

  def rate_take_opts
    { valute: USD, rates_service: ApiClient::Cbr.new }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/_force_rate.html.erb
<%= semantic_form_for [:admin, @resource] do |f| %>
  <%= f.inputs t('active_admin.dashboard.force_rate') do %>
    <%= f.input :rate %>
    <%= f.input :expired_at, as: :date_time_picker, picker_options: { min_date: Date.current, max_date: 2.days.from_now } %>
  <% end %>
  <%= f.button t('active_admin.dashboard.push') %>
<% end %>

app/views/home/index.html.erb
<div class='container home-card__usd-to-rub'>
  <div class='card-deck mb-3 text-center'>
    <div class='card mb-4 shadow-sm'>
      <div class='card-header'>
        <h4 class='my-0 font-weight-normal'>USD to RUB</h4>
      </div>
      <div class='card-body'>
        <h1 class="card-title pricing-card-title" id='usd'> <%= @usd_rate %></h1>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<p class='notice'><%= notice %></p>
<p class='alert'><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class='pt-4 my-md-5 pt-md-5 border-top'>
  <div class='row'>
    <div class='col-12 col-md text-center'>
      <small class='d-block mb-3 text-muted'>© Alexander Abroskin</small>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>iRate</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

app/views/layouts/_nav.html.erb
<div class='d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm'>
  <h5 class='my-0 mr-md-auto font-weight-normal'>iRate</h5>     
  <%= link_to t('admin'), admin_root_path, class: 'btn btn-outline-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render partial: 'layouts/head' %>

  <body>
    <%= render partial: 'layouts/nav' %>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>